apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-alpine-app
  namespace: argocd 
spec:
  project: default  
  source:
    repoURL: https://github.com/madilkhan001/argo-cd-test
    targetRevision: HEAD
    path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
